fix: Add pytest parametrize decorator for model_namespace
- Add @pytest.mark.parametrize decorator to TestEvalHubOTEL class
- Fixes AttributeError: 'SubRequest' object has no attribute 'param'
- model_namespace fixture requires parameters for namespace configuration

Signed-off-by: Karishma Punwatkar <kpunwatk@redhat.com>